### ISSUE TITLE
Define or remove "csgn"

### ISSUE THREAD

**Issue by mhogrefe** [fredrik-johansson/fungrim#17]
I was browsing http://fungrim.org/topic/Inverse_tangent/ and noticed that a few formulas use a `csgn` function that isn't explained anywhere. Is it related to `sgn`? It appears in [formulas/expr.py](https://github.com/fredrik-johansson/fungrim/blob/master/formulas/expr.py) and [formulas/atan.py](https://github.com/fredrik-johansson/fungrim/blob/master/formulas/atan.py).

If `csgn` is just a synonym for `sgn` I can create a pull request to remove it. If it's supposed to be a separate function it should be defined somewhere.

**Comment by fredrik-johansson** [comment]
Many basic functions and operators don't have definitions yet.

Added csgn definition in 59bd45ea108cdbbd82f6a3c38022f1cb5f8016e4

Thanks for reporting the issue!
